apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-prod","kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/ssl-redirect":"true"},"name":"litellm-ingress","namespace":"default"},"spec":{"rules":[{"host":"kailashtech.chickenkiller.com","http":{"paths":[{"backend":{"service":{"name":"litellm","port":{"number":4000}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["kailashtech.chickenkiller.com"],"secretName":"litellm-tls-secret"}]}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  creationTimestamp: "2026-06-07T16:57:11Z"
  generation: 8
  name: litellm-ingress
  namespace: default
  resourceVersion: "659137"
  uid: 6d2b4f85-8d21-4384-8f91-c8e3ce3fa9c8
spec:
  rules:
  - host: kailashtech.chickenkiller.com
    http:
      paths:
      - backend:
          service:
            name: litellm
            port:
              number: 4000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kailashtech.chickenkiller.com
    secretName: litellm-tls-secret
status:
  loadBalancer:
    ingress:
    - hostname: a2f04f75604bf4f4986e350eaf4b6bcb-6b8ac33c01639c4c.elb.ap-south-1.amazonaws.com
